-- source: SON.LUA
-- yeah this ran at runtime and its gonna be shit
-- not gonna be full 
-- run status: finished
-- 48 statements recorded in 0.15s

removed at so its gonna be shit osrry!

local connection = game.AncestryChanged:Connect(function(child, parent)
end)

connection:Disconnect()

local connection2 = workspace.AncestryChanged:Connect(function(child2, parent2)
end)

connection2:Disconnect()
local Folder = Instance.new("Folder")

local connection3 = Folder.AncestryChanged:Connect(function(child3, parent3)
end)

connection3:Disconnect()
Folder:GetChildren()
Folder:Destroy()
local Folder2 = Instance.new("Folder", Folder)

local connection4 = Folder2.AncestryChanged:Connect(function(child4, parent4)
end)

connection4:Disconnect()
Folder2.Name = "382104299"
Folder:WaitForChild("382104299")
Folder:Destroy()
Folder2:Destroy()
local HttpService = game:GetService("HttpService")

local connection5 = HttpService.AncestryChanged:Connect(function(child5, parent5)
end)

connection5:Disconnect()
local RunService = game:GetService("RunService")

local connection6 = RunService.AncestryChanged:Connect(function(child6, parent6)
end)

connection6:Disconnect()
print("hiiiii luraph 14.8")
